version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
    secrets:
      - postgres_passwd
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      retries: 5
      timeout: 5s

  api:
    image: docker.io/library/backend_api:latest
    environment:
      DATABASE_URL: postgresql+psycopg://fastapi:{passwd}@postgres:5432/postgres
      DATABASE_PASSWORD_FILE: /run/secrets/postgres_passwd
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    networks:
      - backend
      - frontend
    secrets:
      - postgres_passwd
      - jwt_secret
    depends_on:
      - postgresql
  frontend:
      image: docker.io/library/frontend_app:latest
      ports:
        - "80:80"
        - "443:443"
      networks:
        - frontend
      depends_on:
        - api

volumes:
  pg_data:
    driver: local
  certs:
    driver: local

networks:
  backend:
    internal: true
  frontend:
    driver: overlay

secrets:
  postgres_passwd:
    external: true
  jwt_secret:
    external: true

